# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: uploadcare
  config:
    publicKey: 9c11eafad01e24a85e2b
    tabs: 'file camera url facebook gdrive'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections: # A list of collections the CMS should be able to edit
  - name: 'pages'
    label: 'Pages'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      # Home Page

      - file: 'content/pages/home.md'
        label: 'Home Page'
        name: 'home-page'
        fields:
          - label: 'Template'
            name: 'template'
            widget: 'hidden'
            default: 'HomePage'

          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }
          - { label: Header Video, name: headerVideo, widget: file }

          - label: 'Portals'
            name: 'portals'
            widget: 'list'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Product Link, name: productLink, widget: string }
              - { label: Distributors Link, name: distLink, widget: string }

          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                  pattern: ['.{,300}', 'Must not exceed 300 characters'],
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      # About Page

      - file: 'content/pages/about.md'
        label: 'About Page'
        name: 'about-page'
        fields:
          - label: 'Template'
            name: 'template'
            widget: 'hidden'
            default: 'AboutPage'

          - { label: Slug, name: slug, widget: hidden, default: 'about' }
          - { label: Title, name: title, widget: string }

          - label: 'About'
            name: 'section1'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: markdown }
              - { label: Image, name: image, widget: image }

          - label: 'Slider'
            name: 'imageSlider'
            widget: 'image'
            required: false
            options: { media_library: { config: { multiple: true } } }

          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                  pattern: ['.{,300}', 'Must not exceed 300 characters'],
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      # Classic Distributors Page

      - file: 'content/pages/classic.md'
        label: 'Classic Distributors Page'
        name: 'classic-distributors-page'
        fields:
          - label: 'Template'
            name: 'template'
            widget: 'hidden'
            default: 'DistributorsPage'

          - {
              label: Slug,
              name: slug,
              widget: hidden,
              default: 'distributors/classic',
            }
          - { label: Title, name: title, widget: string }

          - label: 'Distributors'
            name: 'distributors'
            widget: 'list'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Phone, name: phone, widget: string }
              - { label: Email, name: email, widget: string }
              - { label: Address, name: address, widget: string }
              - { label: Website, name: website, widget: string }

          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                  pattern: ['.{,300}', 'Must not exceed 300 characters'],
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      # Evolution Distributors Page

      - file: 'content/pages/classic.md'
        label: 'Evolution Distributors Page'
        name: 'evolution-distributors-page'
        fields:
          - label: 'Template'
            name: 'template'
            widget: 'hidden'
            default: 'DistributorsPage'

          - {
              label: Slug,
              name: slug,
              widget: hidden,
              default: 'distributors/evolution',
            }
          - { label: Title, name: title, widget: string }

          - label: 'Distributors'
            name: 'distributors'
            widget: 'list'
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Phone, name: phone, widget: string }
              - { label: Email, name: email, widget: string }
              - { label: Address, name: address, widget: string }
              - { label: Website, name: website, widget: string }

          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                  pattern: ['.{,300}', 'Must not exceed 300 characters'],
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      # Contact Page

      - file: 'content/pages/contact.md'
        label: 'Contact Page'
        name: 'contact-page'
        fields:
          - label: 'Template'
            name: 'template'
            widget: 'hidden'
            default: 'ContactPage'

          - { label: Slug, name: slug, widget: hidden, default: 'contact' }
          - { label: Title, name: title, widget: string }
          - { label: Address, name: address, widget: string }
          - { label: Phone, name: phone, widget: string }
          - { label: Email, name: email, widget: string }

          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                  pattern: ['.{,300}', 'Must not exceed 300 characters'],
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

      # Product Index

      - file: 'content/pages/products.md'
        label: 'Products Page'
        name: 'products-page'
        widegt: hidden
        fields:
          - label: 'Template'
            name: 'template'
            widget: 'hidden'
            default: 'ProductIndex'

          - { label: Slug, name: slug, widget: hidden, default: 'products' }
          - { label: Title, name: title, widget: string }

          - label: 'Meta'
            required: false
            name: 'meta'
            widget: 'object'
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - {
                  label: Description,
                  name: description,
                  widget: text,
                  required: false,
                  pattern: ['.{,300}', 'Must not exceed 300 characters'],
                }
              - {
                  label: Canonical Link,
                  name: canonicalLink,
                  widget: string,
                  required: false,
                }
              - {
                  label: Noindex,
                  name: noindex,
                  widget: boolean,
                  required: false,
                }

  # Single Products

  - name: 'products'
    label: 'Products'
    editor:
      preview: true
    folder: 'content/products'
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: 'Template'
        name: 'template'
        widget: 'hidden'
        default: 'SingleProduct'

      - { label: Title, name: title, widget: string }
      - { label: Featured Image, name: featuredImage, widget: image }
      - { label: Overview, name: overview, widget: markdown }

      - label: 'Image Slider'
        name: 'productSlider'
        widget: 'image'
        required: false
        options: { media_library: { config: { multiple: true } } }

      - label: 'Downloads'
        name: 'downloads'
        widget: 'object'
        required: false
        fields:
          - { label: Name, name: name, widget: string, required: false }
          - { label: Link, name: link, widget: file, required: false }

      - label: 'Meta'
        required: false
        name: 'meta'
        widget: 'object'
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - {
              label: Description,
              name: description,
              widget: text,
              required: false,
              pattern: ['.{,300}', 'Must not exceed 300 characters'],
            }
          - {
              label: Canonical Link,
              name: canonicalLink,
              widget: string,
              required: false,
            }
          - { label: Noindex, name: noindex, widget: boolean, required: false }

  # Product Categories

  - name: productCategories
    label: Product Categories
    editor:
      preview: false
    folder: content/productCategories
    slug: '{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: 'Template'
        name: 'template'
        widget: 'hidden'
        default: 'ProductIndex'

      - { label: Title, name: title, widget: string }

  # Settings

  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Header Meta / Scripts,
              name: headerScripts,
              widget: text,
              required: false,
            }
